name: Keep Render Awake

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render App
        run: curl -s "https://google-news-decoder-api.onrender.com/decode?url=http://example.com"
